### ISSUE TITLE
Error Passing mock from mocked interface

### ISSUE THREAD

**Issue by jezzsantos** [florinn/typemoq#70] opened 2017-06-08 21:55 UTC
Not sure if this is exactly the same as what is being see in #67. 
But I am hitting this problem, and its a real show stopper for mocking interfaces.

Given this simple relationship:
```
        interface ISomething{
        }

        class A{
            do():Promise<any>{
                return Promise.resolve({});
            }
        }
```

then this test passes:
```
        it('passes', done => {
            let something: TypeMoq.IMock<ISomething> = TypeMoq.Mock.ofType<ISomething>(); // mocking an interface

            let a:TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>();
            a.setup(x => x.do())
                .returns(() => Promise.resolve({}));

            a.object.do()
                .then(() => {
                    a.verifyAll();
                    done();
                })
        });
```
but this test fails:
```
        it('passes', done => {
            let something: TypeMoq.IMock<ISomething> = TypeMoq.Mock.ofType<ISomething>();

            let a:TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>();
            a.setup(x => x.do())
                .returns(() => Promise.resolve(something.object));

            a.object.do()
                .then(() => {
                    a.verifyAll();
                    done();
                })
        });
```
the only difference is that in the 2nd example we are returning an instance of mocked interface `ISomething`. Whereas in the first example we are returning an actual instance.

**Comment by jezzsantos** [comment] 2017-06-08 22:09
Just to be clear, the issue is only when mocking an interface, since this does work with a class:

Given:
```
        class ASomething{}

        class A{
            do():Promise<any>{
                return Promise.resolve({});
            }
        }
```
then this passes OK:
```
        it('', done => {
            let something: TypeMoq.IMock<ASomething> = TypeMoq.Mock.ofType(ASomething); // mocking a class this time

            let a:TypeMoq.IMock<A> = TypeMoq.Mock.ofType<A>();
            a.setup(x => x.do())
                .returns(() => Promise.resolve(something.object));

            a.object.do()
                .then(() => {
                    a.verifyAll();
                    done();
                })
        });
```

**Comment by florinn** [comment] 2017-06-24 09:37
In the case of dynamic mocking, to make sure the Promise gets resolved properly, you need to turn the mock into a thenable by setting up `.then`:

```
let something: TypeMoq.IMock<ISomething> = TypeMoq.Mock.ofType<ISomething>();
something.setup((x: any) => x.then).returns(() => undefined);
...
```
This is necessary because of the way dynamic mocking works internally. 
More specifically, intercepting method calls with the ES6 Proxy is a two step process and when `Promise.resolve` makes a call to `something.object.then` the process cannot get completed, which in turn leaves the Promise in a pending state.

Indeed it looks like a duplicate of #67, closing this.

**Closed by florinn** 2017-06-24 09:37 UTC

**Comment by jezzsantos** [comment] 2017-06-25 03:22
OK, good to know. thanks. let me see how that feels in practice.
